### ISSUE TITLE
Does not work when Enrollment Flow has T&C set to Ignore 

### ISSUE THREAD

**Issue by panihil** [cilogon/EmailVerificationEnroller#14]
Using COmanage Registry v4.3.5. EmailVerificationEnroller works as expected until we changed the value of " Terms and Conditions Mode" on the enrollment flow from "explicit consent" to "ignore". Once this is set to "ignore", the wedge does not display the screen to enter a code and no email is sent. It also works if the T&C mode is set to "implicit consent", but that is not what is always desired.

**Comment by skoranda** [comment]
@panihil this issue does not happen with the latest version of the plugin so I am going to close this issue. Thanks.

**Comment by skoranda** [comment]
This issue does not happen with the latest version of the plugin so I am going to close this issue.
