### ISSUE TITLE
Change Character Set for Code

### ISSUE THREAD

**Issue by terrencegf** [cilogon/EmailVerificationEnroller#8]
The character set used to generate the code should be configurable, with the following limitations:

1. Only numbers and letters should be allowed.
2. All letters must be upper case.
3. The "default" character set should be "234679CDFGHJKLMNPQRTVWXZ". This character set was chosen using the following criteria:

- No ambiguous characters, e.g., 1 (one), I (uppercase "eye"), and l (lowercase "el") look similar, depending on the font used for rendering the text.
- All uppercase characters. The web browser will use JavaScript to automatically convert lowercase characters to uppercase, e.g., `oninput="this.value = this.value.toUpperCase();"`. Additionally, the web server will ensure all uppercase characters when the web form is submitted.
- No vowels. This reduces the possibility of generating offensive words.

For readability, the code in the email may contain delimiters such as spaces or hyphens, but these extra characters would not need to be entered by the user, and would be allowed (but ignored) if they were entered. An example code: `3MS-PW9C`

**Comment by ioigoume** [comment]
@terrencegf what do you mean `he code should be configurable`. According to the requirements we had so far the administrator can define the length of the code which has to be meet the following criteria:
`Minimum/Default length is 8. Maximum is 20. Length step is 4`. More configuration options are required?

**Comment by terrencegf** [comment]
Sorry I wasn't more explicit. I meant the set of characters used to generate the code should be configurable, e.g., 

```
// Example: allow all upper-case letters and numbers in the code
$code_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
```
If not defined, the default set of characters should be the following.

```
// Default set of characters, if $code_characters is not configured
$code_characters = '234679CDFGHJKLMNPQRTVWXZ';
```

Another example would be to allow only upper-case letters without vowels:

```
// Example: use only upper-case letters, but no vowels, in codes
$code_characters = 'BCDFGHJKLMNPQRSTVWXZ';
```

I would like a slight change to length/step:

```
The default length of code is 8, if $code_length is not configured
The minimum length of code is 4.
The maximum length of code is 20.
The length step is 4. 
```

**Comment by ioigoume** [comment]
@terrencegf please mark the issue as done as soon as you confirm that the latest changes meet the requirements.
Thank you

**Comment by terrencegf** [comment]
I made a few edits to text in `Lib/lang.php`. Otherwise, looks good!
