### ISSUE TITLE
Change Web Form for Entering Code

### ISSUE THREAD

**Issue by terrencegf** [cilogon/EmailVerificationEnroller#9]
The current web form for entering the code looks like this:

![CodeInputCurrent](https://github.com/cilogon/EmailVerificationEnroller/assets/135982/4bab00cc-06e2-4e65-b483-d58ee6f20514)

The web form should be updated to look like this:

![CodeInputDesired](https://github.com/cilogon/EmailVerificationEnroller/assets/135982/fbe3f39a-338b-459b-ac3e-fd23c093850e)

Notes:
1. The text block that begins "DO NOT CLOSE YOUR BROWSER..." should be configurable.
2. The code `<input>` element should be a single text field. If the emailed code contains hyphens or spaces for readability, the text field should allow those extra characters to be entered, but the server should ignore them on submit.
3. The code `<input>` element should have input/tab focus by default.
4. The code `<input>` element should have JavaScript to force any entered letters to uppercase, e.g., `oninput="this.value = this.value.toUpperCase();"` .
5. The "Verification attempt #0" in the current web form should be eliminated. Instead, when a user enters an incorrect code, text at the bottom of the form shows "Invalid code. Please try again."

**Comment by ioigoume** [comment]
New View:
![Screenshot from 2024-02-09 20-20-54](https://github.com/cilogon/EmailVerificationEnroller/assets/3846025/b0ce2f47-8344-402f-ac35-09c80481ed23)

**Comment by terrencegf** [comment]
As of commit https://github.com/cilogon/EmailVerificationEnroller/commit/11f3fc09865ddb97ecbe8d656895047debc1e7bf , I find the following strange behavior for the "Enter Code to Verify Your Email Address" form:

1. If I enter an incorrect code, a new email is sent with a different code, and the first code is invalidated.
1. If I click the "SUBMIT" button when the "Enter Code" field is blank, the form is submitted. I think JavaScript should prevent submitting an empty code.
1. When an incorrect code is entered, the user is shown a countdown timer. Currently, 1 second is added to the timer for each incorrect code. I think timer should double for each incorrect code.
1. I am unable to submit the code by pressing \<ENTER\>. I must click the "SUBMIT" button.

**Comment by terrencegf** [comment]
All feature requests have been addressed as of the [latest commit](https://github.com/cilogon/EmailVerificationEnroller/commit/a9d645475344a00295981888b3d85a6379ce00fd). Closing this issue.
